---
- name: Remove proxmox enterprise repo
  apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise"
    state: absent
  when: no_enterprise|bool
  tags:
    - proxmox
    - sources

- name: Add proxmox no-enterprise repo
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription"
    state: present
  when: no_enterprise|bool
  tags:
    - proxmox
    - sources
...
